### PR TITLE
Use ramsey/uuid v3

### PR DESCRIPTION
**Pull request by bgaleotti**

### CODE REVIEW

**Comment by bgaleotti** [comment]
Ping @wjzijderveld

**Comment by guilhermednt** [comment]
I'd really appreciate this... Pretty please, @wjzijderveld? :)

**Comment by othillo** [comment]
hello, check this PR for a similar request on broadway/uuid-generator like this: https://github.com/qandidate-labs/broadway-uuid-generator/pull/8/files

**Comment by robinvdvleuten** [comment]
please see #10 for some improvements on top of this one.

**Comment by othillo** [comment]
see https://github.com/qandidate-labs/stack-request-id/pull/10

**Comment by othillo** [comment]
solved by #10 
thanks anyway, @bgaleotti !

**Pull request closed without merging**
