### PR TITLE
Add compatibility with symfony 3

### PR DESCRIPTION
**Pull request by olivier34000**

### CODE REVIEW

**Comment by wjzijderveld** [comment]
Thanks @olivier34000

**Comment by olivier34000** [comment]
Thanks @wjzijderveld 
Is-it possible to create a new tag on master ?

**Comment by wjzijderveld** [comment]
Better late then never :sweat_smile: 

0.4.0 has been released https://github.com/qandidate-labs/stack-request-id/releases/tag/0.4.0

**Comment by olivier34000** [comment]
thanks you :+1:

**Pull request merged**
