### PR TITLE
Update composer.json to require new name but old package inside :)

### LINKED ISSUE #2: switch to ramsey/uuid?

### PR DESCRIPTION
**Pull request by cordoval**
fixes #2

### CODE REVIEW

**Comment by wjzijderveld** [comment]
Why also update the version? ~2.0 should still work?

**Comment by wjzijderveld** [comment]
@cordoval ping? :)

**Comment by cordoval** [comment]
I agree with you I guess, you are the maintainer so you know best.

**Comment by wjzijderveld** [comment]
@cordoval I didn't mean to close it, I only asked about the version bump. I still want to merge the name change...

**Pull request closed without merging**
