### PR TITLE
Add support for sending the request id with a response.

### PR DESCRIPTION
**Pull request by jakzal**
I've got a requirement for this feature. I could write a new middleware, but I think it makes sense to support it here.

The feature is made optional.

### CODE REVIEW

**Comment by asm89** [comment]
:+1:

**Comment by wjzijderveld** [comment]
Awesome, thanks @jakzal

**Comment by jakzal** [comment]
Any chance for a tag? ;)

**Comment by jakzal** [comment]
That was quick. Thanks! :beers:

**Comment by wjzijderveld** [comment]
Because you asked nicely: :tada: https://github.com/qandidate-labs/stack-request-id/releases/tag/0.2.0
:smile:

**Pull request merged**
